### PR TITLE
Ensure compatibility with Play 2.4

### LINKED ISSUE #13: play 2.4 compatibility
It seems that the json library in play 2.4 is incompatible with geosjon 1.2.0

```
java.lang.NoSuchMethodError: play.api.data.validation.ValidationError.<init>(Ljava/lang/String;Lscala/collection/Seq;)V
    at play.extras.geojson.GeoFormats$.filterType(GeoJson.scala:277)
```

### PR DESCRIPTION
**Pull request by jroper**
Fixes #13

This should also be binary compatible with Play 2.3, since ValidationError.apply(message: String, args: Any*) exists on both Play 2.4 and Play 2.3.

### CODE REVIEW

**Comment by jroper** [comment]
Hmm... it was already fixed.  Nevertheless, this fix should be binary compatible, allowing the latest to work with Play 2.3 and Play 2.4.

**Comment by muuki88** [comment]
Great! Thanks :)
